/*
 * Squadlist
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.squadlist.model.swagger;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import uk.co.squadlist.model.swagger.AvailabilityOption;
import uk.co.squadlist.model.swagger.Member;
import uk.co.squadlist.model.swagger.Outing;

/**
 * Availability
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-23T12:06:48.563+01:00")
public class Availability {
  @SerializedName("member")
  private Member member = null;

  @SerializedName("outing")
  private Outing outing = null;

  @SerializedName("availabilityOption")
  private AvailabilityOption availabilityOption = null;

  public Availability member(Member member) {
    this.member = member;
    return this;
  }

   /**
   * Get member
   * @return member
  **/
  @ApiModelProperty(required = true, value = "")
  public Member getMember() {
    return member;
  }

  public void setMember(Member member) {
    this.member = member;
  }

  public Availability outing(Outing outing) {
    this.outing = outing;
    return this;
  }

   /**
   * Get outing
   * @return outing
  **/
  @ApiModelProperty(required = true, value = "")
  public Outing getOuting() {
    return outing;
  }

  public void setOuting(Outing outing) {
    this.outing = outing;
  }

  public Availability availabilityOption(AvailabilityOption availabilityOption) {
    this.availabilityOption = availabilityOption;
    return this;
  }

   /**
   * Get availabilityOption
   * @return availabilityOption
  **/
  @ApiModelProperty(value = "")
  public AvailabilityOption getAvailabilityOption() {
    return availabilityOption;
  }

  public void setAvailabilityOption(AvailabilityOption availabilityOption) {
    this.availabilityOption = availabilityOption;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Availability availability = (Availability) o;
    return Objects.equals(this.member, availability.member) &&
        Objects.equals(this.outing, availability.outing) &&
        Objects.equals(this.availabilityOption, availability.availabilityOption);
  }

  @Override
  public int hashCode() {
    return Objects.hash(member, outing, availabilityOption);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Availability {\n");
    
    sb.append("    member: ").append(toIndentedString(member)).append("\n");
    sb.append("    outing: ").append(toIndentedString(outing)).append("\n");
    sb.append("    availabilityOption: ").append(toIndentedString(availabilityOption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

