/*
 * Squadlist
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.squadlist.model.swagger;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * Statistics
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-06T09:59:33.441+01:00")
public class Statistics {
  @SerializedName("totalMembersCount")
  private BigDecimal totalMembersCount = null;

  @SerializedName("totalOutingsCount")
  private BigDecimal totalOutingsCount = null;

  @SerializedName("recentMembersCount")
  private BigDecimal recentMembersCount = null;

  @SerializedName("latestOutingDate")
  private OffsetDateTime latestOutingDate = null;

  public Statistics totalMembersCount(BigDecimal totalMembersCount) {
    this.totalMembersCount = totalMembersCount;
    return this;
  }

   /**
   * Get totalMembersCount
   * @return totalMembersCount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getTotalMembersCount() {
    return totalMembersCount;
  }

  public void setTotalMembersCount(BigDecimal totalMembersCount) {
    this.totalMembersCount = totalMembersCount;
  }

  public Statistics totalOutingsCount(BigDecimal totalOutingsCount) {
    this.totalOutingsCount = totalOutingsCount;
    return this;
  }

   /**
   * Get totalOutingsCount
   * @return totalOutingsCount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getTotalOutingsCount() {
    return totalOutingsCount;
  }

  public void setTotalOutingsCount(BigDecimal totalOutingsCount) {
    this.totalOutingsCount = totalOutingsCount;
  }

  public Statistics recentMembersCount(BigDecimal recentMembersCount) {
    this.recentMembersCount = recentMembersCount;
    return this;
  }

   /**
   * Get recentMembersCount
   * @return recentMembersCount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getRecentMembersCount() {
    return recentMembersCount;
  }

  public void setRecentMembersCount(BigDecimal recentMembersCount) {
    this.recentMembersCount = recentMembersCount;
  }

  public Statistics latestOutingDate(OffsetDateTime latestOutingDate) {
    this.latestOutingDate = latestOutingDate;
    return this;
  }

   /**
   * Get latestOutingDate
   * @return latestOutingDate
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getLatestOutingDate() {
    return latestOutingDate;
  }

  public void setLatestOutingDate(OffsetDateTime latestOutingDate) {
    this.latestOutingDate = latestOutingDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Statistics statistics = (Statistics) o;
    return Objects.equals(this.totalMembersCount, statistics.totalMembersCount) &&
        Objects.equals(this.totalOutingsCount, statistics.totalOutingsCount) &&
        Objects.equals(this.recentMembersCount, statistics.recentMembersCount) &&
        Objects.equals(this.latestOutingDate, statistics.latestOutingDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalMembersCount, totalOutingsCount, recentMembersCount, latestOutingDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Statistics {\n");
    
    sb.append("    totalMembersCount: ").append(toIndentedString(totalMembersCount)).append("\n");
    sb.append("    totalOutingsCount: ").append(toIndentedString(totalOutingsCount)).append("\n");
    sb.append("    recentMembersCount: ").append(toIndentedString(recentMembersCount)).append("\n");
    sb.append("    latestOutingDate: ").append(toIndentedString(latestOutingDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

